// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4ydrgNiUruruIfSU8WvhyXkX3eJD2IQ',
    appId: '1:895738126448:web:06f2e8210d483e292cd4b5',
    messagingSenderId: '895738126448',
    projectId: 'cloudbook-fc683',
    authDomain: 'cloudbook-fc683.firebaseapp.com',
    databaseURL: 'https://cloudbook-fc683-default-rtdb.firebaseio.com',
    storageBucket: 'cloudbook-fc683.appspot.com',
    measurementId: 'G-10RKH0455D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkBE-dux7gfIBlnrqGW1ms-Ps7IWaJYo',
    appId: '1:895738126448:android:1e6d1c1891816c632cd4b5',
    messagingSenderId: '895738126448',
    projectId: 'cloudbook-fc683',
    databaseURL: 'https://cloudbook-fc683-default-rtdb.firebaseio.com',
    storageBucket: 'cloudbook-fc683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqVAtdkQAvDmRXwA_BoJi0jN_2izjmAI',
    appId: '1:895738126448:ios:55f89d7d486ac8432cd4b5',
    messagingSenderId: '895738126448',
    projectId: 'cloudbook-fc683',
    databaseURL: 'https://cloudbook-fc683-default-rtdb.firebaseio.com',
    storageBucket: 'cloudbook-fc683.appspot.com',
    iosBundleId: 'cloudbook.br.cloudbook',
  );
}
